
services:
  web:
    image: nginx
    ports:
      - "8081:81"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

    networks:
        - default

  php-fpm:
    build: ../online-shop-laravel/docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini
    networks:
        - default
    depends_on:
        - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54320:5432"

    networks:
        - default

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - "5672:5672"
          - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq

  mailpit:
      image: axllent/mailpit:latest
      container_name: mailpit
      restart: unless-stopped
      ports:
         - "8025:8025" # веб-интерфейс
         - "1025:1025" # smtp-сервер
      networks:
          - default

  redis:
      image: redis:alpine
      container_name: redis
      ports:
          - "6379:6379"
      restart: unless-stopped


volumes:
    rabbitmq_data:
    postgres_data:


