
services:
  web:
    image: nginx
    ports:
      - "8081:81"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php-fpm:
    build: ../online-shop-laravel/docker/php
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54320:5432"

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - "5672:5672"
          - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq

volumes:
    rabbitmq_data:
